artifacts_roots: artifacts

data_ingestion:
  root_dir: aretifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  local_data_file: aretifacts/data_ingestion/data.zip
  unzip_dir: aretifacts/data_ingestion


prepare_base_model:
  root_dir: aretifacts/prepare_base_model
  base_model_path: aretifacts/prepare_base_model/base_model.h5
  updated_base_model_path: aretifacts/prepare_base_model/base_model_updated.h5
  
